# Generated by Django 3.0.5 on 2023-05-08 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=20)),
                ('dr_adress', models.CharField(max_length=20)),
                ('dr_phone_number', models.CharField(max_length=11)),
                ('dr_description', models.CharField(max_length=200)),
                ('slug', models.CharField(blank=True, max_length=1000, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city', to='listoflist.city')),
            ],
        ),
    ]
