# Generated by Django 4.2.1 on 2023-05-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listoflist', '0002_alter_city_id_alter_doctor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='slug',
        ),
    ]
