# Generated by Django 4.2.1 on 2023-05-27 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listoflist', '0004_alter_doctor_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='dr_description',
        ),
    ]
