# Generated by Django 4.2.1 on 2023-07-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listoflist', '0005_remove_doctor_dr_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dr_adress',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dr_name',
            field=models.CharField(max_length=90),
        ),
    ]
