# Generated by Django 4.2.1 on 2023-05-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='imagepath',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
