# Generated by Django 4.2.1 on 2023-05-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_classifier_imagepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifier',
            name='imagepath',
        ),
    ]
