# Generated by Django 4.2.1 on 2023-05-19 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ml', '0003_remove_classifier_imagepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='user',
            field=models.ForeignKey(default=89, on_delete=django.db.models.deletion.CASCADE, related_name='user_prediction', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
