# Generated by Django 4.2.1 on 2023-05-23 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0004_classifier_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifier',
            name='user',
        ),
    ]
