# Generated by Django 4.2.1 on 2023-05-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0006_classifier_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifier',
            name='user',
        ),
        migrations.AlterField(
            model_name='classifier',
            name='image',
            field=models.ImageField(blank=True, upload_to='ml/image/'),
        ),
        migrations.AlterField(
            model_name='classifier',
            name='prediction',
            field=models.CharField(max_length=100),
        ),
    ]
