# Generated by Django 4.2.1 on 2023-05-26 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ml', '0007_remove_classifier_user_alter_classifier_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='preuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='ml/image/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
