# Generated by Django 4.2.1 on 2023-05-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0008_preuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='classifier',
        ),
    ]
